// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.trackerclient {
    exports com.timboudreau.trackerclient;
    exports com.timboudreau.trackerclient.impl;
    exports com.timboudreau.trackerclient.pojos;

    // derived from com.google.guava/guava-31.1-jre in com/google/guava/guava/31.1-jre/guava-31.1-jre.pom
    requires transitive com.google.common;

    // Sibling com.mastfrog/generic-web-api-3.0.0-dev
    requires com.mastfrog.generic.web.api;

    // Transitive detected by source scan
    requires com.mastfrog.giulius;

    // Sibling com.mastfrog/jackson-3.0.0-dev
    requires com.mastfrog.jackson;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.time;

    // Transitive detected by source scan
    requires com.mastfrog.trackerapi;

    // Inferred from source scan
    requires com.mastfrog.util.function;

    // derived from com.fasterxml.jackson.core/jackson-annotations-0.0.0-? in com/fasterxml/jackson/core/jackson-annotations/2.9.5/jackson-annotations-2.9.5.pom
    requires transitive jackson.annotations;

    // derived from com.fasterxml.jackson.core/jackson-core-0.0.0-? in com/fasterxml/jackson/core/jackson-core/2.9.9/jackson-core-2.9.9.pom
    requires transitive jackson.core;

    // Inferred from test-source-scan
    requires transitive junit;

}
