open module com.mastfrog.trackerclient {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.timboudreau.trackerclient;
    exports com.timboudreau.trackerclient.impl;
    exports com.timboudreau.trackerclient.pojos;

    // derived from com.fasterxml.jackson.core/jackson-annotations-2.13.2 in com/fasterxml/jackson/core/jackson-annotations/2.13.2/jackson-annotations-2.13.2.pom
    requires transitive com.fasterxml.jackson.annotation;

    // derived from com.fasterxml.jackson.core/jackson-core-2.13.2 in com/fasterxml/jackson/core/jackson-core/2.13.2/jackson-core-2.13.2.pom
    requires transitive com.fasterxml.jackson.core;

    // derived from com.google.guava/guava-31.1-jre in com/google/guava/guava/31.1-jre/guava-31.1-jre.pom
    requires transitive com.google.guava.guava;
    requires transitive com.mastfrog.acteur.mongo;
    requires transitive com.mastfrog.generic.web.api;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.jackson;
    requires transitive com.mastfrog.netty.http.test.harness;
    requires transitive com.mastfrog.trackerapi;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
